### ISSUE TITLE
Strong name sign package

### ISSUE THREAD

**Issue by caesay** [roryprimrose/Neovolve.Logging.Xunit#237]
Thanks for a great library! Unfortunately it's not possible to use when testing strong name signed assemblies on netfx, because this library is not strong name signed itself.

Would be great if that could be added!

**Comment by roryprimrose** [comment]
Thank you for the ask. I do not have any intention of strong naming this assembly.

**Comment by caesay** [comment]
Okay, in that case I'll fork it and publish a strong name signed version on NuGet, eg. `Neovolve.Logging.Xunit.StrongName`. Thanks.

**Comment by roryprimrose** [comment]
There have been more asks for this. I have published this to [Neovolve.Logging.Xunit.Signed](https://www.nuget.org/packages/Neovolve.Logging.Xunit.Signed)
