### ISSUE TITLE
Support for xUnit v3

### ISSUE THREAD

**Issue by craigktreasure** [roryprimrose/Neovolve.Logging.Xunit#301]
Just curious if you had plans to support xUnit v3. Biggest hang up appears to be that `xunit.abstractions` was deprecated and the `ITestOutputHelper` type was moved to the `xunit.v3` package.

See [migration guide](https://xunit.net/docs/getting-started/v3/migration) and [what's new](https://xunit.net/docs/getting-started/v3/whats-new).

**Comment by roryprimrose** [comment]
Yes I definitely will. 

The biggest decision is whether it will a major version bump under the existing package id or a new package called `Neovolve.Logging.Xunit.v3`. 

I'm leaning towards a new package name as this allows both versions to be easily used in the same repo. The big advantage here is that larger repositories can do a staged migration between the two versions of xunit. Where centralised package management and transitive version pinning is used, this also means that version overrides would not be required.

**Comment by roryprimrose** [comment]
I've done the initial attempt at this conversion however I'm hitting a conflict on automatically generated main methods what no-one else seems to have hit.

**Comment by roryprimrose** [comment]
Beta builds are published to MyGet for [Neovolve.Logging.Xunit.v3](https://www.myget.org/feed/neovolve/package/nuget/Neovolve.Logging.Xunit.v3/7.0.0-xunit-v3-0009) and [Neovolve.Logging.Xunit.Signed.v3](https://www.myget.org/feed/neovolve/package/nuget/Neovolve.Logging.Xunit.Signed.v3/7.0.0-xunit-v3-0009).

If you have time to validate those packages I'd appreciate the feedback.

**Comment by craigktreasure** [comment]
So far so good on 1 of my projects using `7.0.0-xunit-v3-0009`.

**Comment by roryprimrose** [comment]
Version `7.0.0-beta0006` has been released to [nuget.org](https://www.nuget.org/packages/Neovolve.Logging.Xunit.v3#readme-body-tab) to support xUnit v3. I'll leave it in beta and do some further validation before making it a production release.

**Comment by nrhoffmann** [comment]
@roryprimrose Can you please post here when it is released to production?

**Comment by roryprimrose** [comment]
Version [Neovolve.Logging.Xunit.v3 7.0.0](https://www.nuget.org/packages/Neovolve.Logging.Xunit.v3) has been released to support xUnit v3
